---
title: "Penguins ANOVA"
author: "Gage Clawson"
date: "11/6/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include = FALSE}

library(tidyverse)
library(car)
library(onewaytests)

penguins <- read_csv("penguins.csv")
```


Is there a significant difference in mean flipper length for female penguins by species (chinstrap, gentoo, adelie)?


Do some exploring

New functions: with + table for easy counting over multiple factors

Update species name using case_when

```{r}
counts <- with(penguins, table(species, sex))

penguins2 <- penguins %>%
  mutate(common_name = 
           case_when(
             species == "Chinstrap penguin (Pygoscelis antarctica)" ~ "Chinstrap",
             species == "Gentoo penguin (Pygoscelis papua)" ~ "Gentoo",
             species == "Adelie Penguin (Pygoscelis adeliae)" ~ "Adelie"
           )
         ) %>%
  select(-species) %>%
  filter(sex == "FEMALE")


```

- Exploratory graphs
- Summary statistics 
- Levene's tests for equal variances 
- 1 - way ANOVA
- Post hoc testing


```{r}
hists <- ggplot(penguins2, aes(x = flipper_length)) +
  geom_histogram(aes(fill = common_name)) + 
  facet_wrap(~common_name)

hists

qq <- ggplot(penguins2, aes(sample = flipper_length)) +
  geom_qq() +
  facet_wrap(~common_name)

qq


# Levene's test for equal variances (>2 groups... if you have two groups use the F-test for equal variances)

# We'll use the function leveneTest from the 'car' package

# H0: Variances are equal
# HA: Variances are unequal

penguin_levene <- leveneTest(flipper_length ~ common_name, data = penguins2)
penguin_levene

# we retain the null hypothesis of equal variances (p = 0.06)

var_table <- penguins2 %>%
  group_by(common_name) %>%
  summarise(variance = var(flipper_length))

# if largest variance < 4X larger than the smallest variance, can still use ANOVA


```


